name: CI Pipeline

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: 1. Verificação de Estilo (Lint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Instalar dependências
        run: npm ci

      - name: Rodar verificação de lint

        run: npm run lint

  test-coverage:
    name: 2. Testes e Cobertura (90%)
    runs-on: ubuntu-latest

    needs: lint

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes e verificar cobertura
        run: npm test -- --coverage
  build-docker:
    name: 3. Construção da Imagem Docker
    runs-on: ubuntu-latest
    needs: test-coverage
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir Imagem (Build)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-filmes:${{ github.sha }}
          outputs: type=docker,dest=/tmp/api-filmes.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-filmes
          path: /tmp/api-filmes.tar

  scan-docker:
    name: 4. Scan de Vulnerabilidades (Trivy)
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-filmes
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/api-filmes.tar

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ secrets.DOCKERHUB_USERNAME }}/api-filmes:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

  publish-docker:
    name: 5. Publicação no DockerHub
    runs-on: ubuntu-latest
    needs: scan-docker
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-filmes:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/api-filmes:latest
